### ISSUE TITLE
Plumed 2.5 compile with OpenMM 7.4.0 failed

### ISSUE THREAD

**Issue by CryoSky** [plumed/plumed2#604]
Hello,
I tried to install the openMM-plumed plugin in my computer from https://github.com/openmm/openmm-plumed. However, an error occured like the below:

/home/sj52/anaconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: warning: libplumedKernel.so, needed by /home/sj52/Backup/plumed_254/lib/libplumed.so, not found (try using -rpath or -rpath-link)
/home/sj52/anaconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/sj52/Backup/plumed_254/lib/libplumed.so: undefined reference to `plumed_symbol_table_init'
/home/sj52/anaconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/sj52/Backup/plumed_254/lib/libplumed.so: undefined reference to `plumed_symbol_table'
collect2: error: ld returned 1 exit status
make[2]: *** [platforms/reference/tests/TestReferencePlumedForce] Error 1
make[1]: *** [platforms/reference/tests/CMakeFiles/TestReferencePlumedForce.dir/all] Error 2
make: *** [all] Error 2.

I googled this error and it seems this error only occurs in plumed 2.5 vesion like this issue #429  reported. However, I tried to add the installed lib path as well as the /usr/local/lib to LD_LIBRARY_PATH, but it still failed after I restart the terminal. When I type `echo $LD_LIBRARY_PATH`, I got 

/usr/local/lib:/home/sj52/Backup/plumed_254/lib:/usr/local/cuda-10.1/lib64:/opt/rice/gromacs-2020.0/cuda-10.1/lib64:/usr/local/cuda-10.1/lib64

so it seems the right path has already added to the LD_LIBRARY_PATH. But the compile process is still failed. I use the Red Hat 7.0 system and compile with `ccmake .`. I also gave the right path for the plumed related options:

PLUMED_BUILD_CUDA_LIB            ON                                                                                                                                                                              
PLUMED_BUILD_OPENCL_LIB          ON                                                                                                                                                                              
PLUMED_BUILD_PYTHON_WRAPPERS     ON                                                                                                                                                                              
PLUMED_INCLUDE_DIR               /home/sj52/Backup/plumed_254/include/plumed                                                                                                                                     
PLUMED_LIBRARY_DIR               /home/sj52/Backup/plumed_254/lib                                                                                                                                                

Could anyone give some suggestions on how to debug this? Many thanks in advance!
Best wishes,
Shikai

**Comment by CryoSky** [comment]
Besides, I have added right path of libplumedKernel.so to the environmental variable "PLUMED_KERNEL"

**Comment by CryoSky** [comment]
Sorry I figured out by myself. The C++ compiler I given is the one inside the anaconda environment. So whatever the LD_LIBRARY_PATH I set is useless and the compiler cannot find the libplumedKernel.so. I install the Plumed use conda and passed this error. I finally realized the plumed put its file in the anaconda environment's lib directory so the C++ compiler could find it easily. I think the one can also add "-WL,-rpath,/home/sj52/Backup/plumed_254/lib -Wl,-rpath-link,/home/sj52/Backup/plumed_254/lib" to the CMAKE_EXE_LINKER_FLAGS, CMAKE_MODULE_LINKER_FLAGS and CMAKE_SHARED_LINKER_FLAGS options in the ccmake advanced GUI when you tried to compile an external installed Plumed.

**Comment by GiovanniBussi** [comment]
This is a known issue with conda compilers on Linux. Indeed, the way we solve it when we build plumed for conda-forge is to use the `-Wl,-rpath-link` flag (see [this link](https://github.com/plumed/plumed2/blob/779939c00675315729e682243e1626f14e3f22e5/conda/plumed/build.sh#L8)).
