### ISSUE TITLE
`--enable-booth_graph` fails with compilation error

### ISSUE THREAD

**Issue by jhgoebbert** [plumed/plumed2#1294]
Building the current code with `--enable-booth_graph` and Boost 1.86.0 fails with
```
DFSClustering.cpp: In member function virtual void PLMD::clusters::DFSClustering::performClustering():
DFSClustering.cpp:107:3: error: retrieveEdgeList was not declared in this scope; did you mean retrieveAdjacencyLists?
  107 |   retrieveEdgeList( 0, nedges );
      |   ^~~~~~~~~~~~~~~~
      |   retrieveAdjacencyLists
DFSClustering.cpp:110:73: error: std::vector<std::pair<unsigned int, unsigned int> > PLMD::matrixtools::MatrixOperationBase::pairs is private within this context
  110 |   boost::adjacency_list<boost::vecS,boost::vecS,boost::undirectedS> sg(&pairs[0],&pairs[nedges],getNumberOfNodes());
      |                                                                         ^~~~~
matrixtools/../../matrixtools/MatrixOperationBase.h:38:46: note: declared private here
   38 |   std::vector<std::pair<unsigned,unsigned> > pairs;
      |                                              ^~~~~
DFSClustering.cpp:110:83: error: std::vector<std::pair<unsigned int, unsigned int> > PLMD::matrixtools::MatrixOperationBase::pairs is private within this context
  110 |   boost::adjacency_list<boost::vecS,boost::vecS,boost::undirectedS> sg(&pairs[0],&pairs[nedges],getNumberOfNodes());
      |                                                                                   ^~~~~
```

**Comment by ostueker** [comment]
I see the same when trying to compile PLUMED 2.10.0 (albeit with Boost 1.85.0):

```
compiling  DFSClustering.cpp
DFSClustering.cpp: In member function ‘virtual void PLMD::clusters::DFSClustering::performClustering()’:
DFSClustering.cpp:115:3: error: ‘retrieveEdgeList’ was not declared in this scope; did you mean ‘retrieveAdjacencyLists’?
  115 |   retrieveEdgeList( 0, nedges );
      |   ^~~~~~~~~~~~~~~~
      |   retrieveAdjacencyLists
DFSClustering.cpp:118:73: error: ‘std::vector<std::pair<unsigned int, unsigned int> > PLMD::matrixtools::MatrixOperationBase::pairs’ is private within this context
  118 |   boost::adjacency_list<boost::vecS,boost::vecS,boost::undirectedS> sg(&pairs[0],&pairs[nedges],getNumberOfNodes());
      |                                                                         ^~~~~
In file included from matrixtools/MatrixOperationBase.h:1,
                 from ClusteringBase.h:25,
                 from DFSClustering.cpp:22:
matrixtools/../../matrixtools/MatrixOperationBase.h:38:46: note: declared private here
   38 |   std::vector<std::pair<unsigned,unsigned> > pairs;
      |                                              ^~~~~
DFSClustering.cpp:118:83: error: ‘std::vector<std::pair<unsigned int, unsigned int> > PLMD::matrixtools::MatrixOperationBase::pairs’ is private within this context
  118 |   boost::adjacency_list<boost::vecS,boost::vecS,boost::undirectedS> sg(&pairs[0],&pairs[nedges],getNumberOfNodes());
      |                                                                                   ^~~~~
matrixtools/../../matrixtools/MatrixOperationBase.h:38:46: note: declared private here
   38 |   std::vector<std::pair<unsigned,unsigned> > pairs;
      |                                              ^~~~~
make[6]: *** [../maketools/make.rules:21: DFSClustering.o] Error 1
```

**Comment by ostueker** [comment]
Indeed, not using `--enable-boost_graph` lets me build PLUMED 2.10.0.

This is not related to the version of Boost (I've tried with 1.82.0 and 1.85.0)
and building with `--enable-boost_graph` worked with PLUMED 2.9.4 just last week, so this bug must have been introduced on the 2.10 branch.
